### ISSUE TITLE
sp-akod00

### ISSUE THREAD

**Issue by hailstorm75** [nvbach91/4IZ278-2020-2021-LS#120]
# MeetNow
Cílem aplikace je umožnit zaregistrovaným uživatelům vytvářet návrhy dat pro určitou událost, zvolení 
vhodných dat uživateli pozvaných do dané událost, a následné nalezení nejvhodnějšího data pro všechny 
účastníky události.

viz. přiložený dokument: [MeetNow.pdf](https://github.com/nvbach91/4IZ278-2020-2021-LS/files/6259366/MeetNow.pdf)

**Comment by nvbach91** [comment]
1. data, tim myslite datumy a cas?
1. tabulku account prejmenuje na user
1. k cemu jsou sloupce normalized? pro vyhedavani?
1. vztah mezi account a meeting neni potreba
1. meeting prejmenovat na event
1. u meetingu by bylo dobre evidovat i kod, referenci na datumy a casy zahajeni a dobu trvani
1. u casovych navrhu je lepsi uvest pro kterou udalost je navrzen - nevidim vztah mezi meetingem a available date
1. jakou granularitu budete resit u casovych slotu?
1. muze uzivatel navrhnout jakykoliv cas ke konkretni udalosti?

**Comment by hailstorm75** [comment]
[MeetNow.pdf](https://github.com/nvbach91/4IZ278-2020-2021-LS/files/6289428/MeetNow.pdf)

Upraveno na zaklade poznamek a konzultace.

> Note: kod pro udalost bude id udalosti. Id bude string ve tvaru GUID

**Comment by hailstorm75** [comment]
[MeetNow.pdf](https://github.com/nvbach91/4IZ278-2020-2021-LS/files/6313524/MeetNow.pdf)

Finalni uprava chyb.

Semestralka bude vyvijena v danem repo: https://github.com/hailstorm75/MeetNow

**Comment by nvbach91** [comment]
ok

**Comment by nvbach91** [comment]
#233
