### ISSUE TITLE
Parametry pro pripojeni k databazi na eso

### ISSUE THREAD

**Issue by vonm10** [nvbach91/4IZ278-2020-2021-LS#146]
Poradil by mi prosim nekdo jake parametry pouzit pro pripojeni php k databazi na https://eso.vse.cz/phpmyadmin/ Diky

**Comment by nvbach91** [comment]
phpmyadmin: https://eso.vse.cz/phpmyadmin/ 
username: xname
heslo: obsah souboru **/home/xname/mysql-heslo.txt**

a v PHP:
```php
new PDO(
  "mysql:host=localhost;dbname=xname;charset=utf8mb4",
  "xname",
  "/home/xname/mysql-heslo.txt" // napr. abcdefghijklmnopqrstuvwxyz1234567890
);
```

**Comment by vonm10** [comment]
Dekuji moc
