### ISSUE TITLE
Nelze pushovat do mého repozitáře

### ISSUE THREAD

**Issue by kubakriz** [nvbach91/4IZ278-2020-2021-LS#158]
Krásný den,

tak já nevím, přes upload files nemůžu k CV01 dohrát logo, ani vlastně nic jiného do své krij09 složky nahrát. Když čtu návod, tak nedělám nic jinak, na to vlákno s username na přidělení práv jsem tehdy zavčasu odpověděl... Takže, nevíte, kde je problém? Píše mi to, že nemám práva uploadovat. 
Děkuji.

S pozdravem,
J. Kříž

**Comment by nvbach91** [comment]
odklikat https://github.com/nvbach91/4IZ278-2020-2021-LS/invitations
