### ISSUE TITLE
sp-podj00

### ISSUE THREAD

**Issue by jpodestat** [nvbach91/4IZ278-2020-2021-LS#178]
V přiloženém pdf dokumentu popisuji téma mé semestrální práce. 
[Fictive Fitness.pdf](https://github.com/nvbach91/4IZ278-2020-2021-LS/files/6299476/Fictive.Fitness.pdf)

**Comment by nvbach91** [comment]
Architektura: rozepiste seznam predpokladanych stranek (soubory php, na ktere bude volat prohlizec) nebo pojmenujte ty wireframy

**Comment by jpodestat** [comment]
Dopsáno v dokumentu:
[Fictive Fitness.pdf](https://github.com/nvbach91/4IZ278-2020-2021-LS/files/6323921/Fictive.Fitness.pdf)

**Comment by nvbach91** [comment]
#240
