### ISSUE TITLE
sp-vitl03

### ISSUE THREAD

**Issue by lukas-vit** [nvbach91/4IZ278-2020-2021-LS#179]
Posílám téma své semestrální práce.
[Active.pdf](https://github.com/nvbach91/4IZ278-2020-2021-LS/files/6304777/Active.pdf)

**Comment by nvbach91** [comment]
Architektura: rozepiste seznam predpokladanych stranek (soubory php, na ktere bude volat prohlizec)

**Comment by lukas-vit** [comment]
Přídávám schéma stránek, na které budu volat php. Schéma je v sekci architektura.
[Active.pdf](https://github.com/nvbach91/4IZ278-2020-2021-LS/files/6322680/Active.pdf)

**Comment by nvbach91** [comment]
#245
