### ISSUE TITLE
sp-bejj01

### ISSUE THREAD

**Issue by bejjak** [nvbach91/4IZ278-2020-2021-LS#180]
V příloženém souboru zasílám popis návrhu semestrální práce.
[SportTicket.pdf](https://github.com/nvbach91/4IZ278-2020-2021-LS/files/6306255/SportTicket.pdf)

**Comment by nvbach91** [comment]
Architektura: rozepiste seznam predpokladanych stranek/endpointu (soubory php, na ktere bude volat prohlizec)

**Comment by nvbach91** [comment]
#257
