### ISSUE TITLE
sp-gulm04

### ISSUE THREAD

**Issue by guliamar** [nvbach91/4IZ278-2020-2021-LS#181]
návrh semestrální práce

[sp-gulm04.zip](https://github.com/nvbach91/4IZ278-2020-2021-LS/files/6306743/sp-gulm04.zip)

**Comment by nvbach91** [comment]
Architektura: rozepiste seznam predpokladanych stranek/endpointu (soubory php, na ktere bude volat prohlizec) + jejich wireframe

**Comment by guliamar** [comment]
[sp-gulm04-fixes.pdf](https://github.com/nvbach91/4IZ278-2020-2021-LS/files/6350502/sp-gulm04-fixes.pdf)
pospala jsem architekturu a udělala jsem screenshoty z souboru sp-gulm04.xd z wireframe se stránkami
