### ISSUE TITLE
sp-kadm08

### ISSUE THREAD

**Issue by maiaj** [nvbach91/4IZ278-2020-2021-LS#185]
### Rezervační systém coworkingového centra

Aplikace bude umožňovat správu coworkingového centra. Bude rozlišovat klientskou a administrátorskou část, do kterých se uživatel dostane po přihlášení. Klientská  část umožní uživateli vytvořit si účet v coworkingovém centru a následně si rezervovat pracovní místo. V administrativní části bude možné zobrazit si aktuální stav pracovních míst a editovat je.

**Klientská část**
Po registraci a přihlášení se klientovi zobrazí přehled jeho rezervací pracovních míst, ve kterém uvidí svoje aktuální i historické rezervace. Zároveň si bude moci zarezervovat nové místo. Vybírá si od kdy do kdy místo chce a systém mu pak podle toho přiřadí volné místo (místo musí být vždy volné celé vybrané období, není možné v jedné rezervaci kombinovat více pracovních míst, např. na první půlku měsíce místo A a na druhou místo B). Pokud chce klient vytvořit více rezervací najednou (např. na duben a pak na červen) musí si vytvořit 2 samostatné rezervace. Po vybrání datumů se klientovi zobrazí shrnutí objednávky s přiděleným místem, časovým obdobím a cenou, které musí závazně potvrdit. Vytvořená rezervace se mu poté zobrazí v aktuálních rezervacích. U každé aktivní rezervace bude zobrazen stav: zaplacená/nezaplacená. Bude ji možno editovat nebo zrušit. Rezervace se přepne na neaktivní po skončení vybraného časového období. 

Klient si po zalogování může zároveň zobrazit svoje osobní údaje a editovat je.     
 
**Administrátorská část**
Administrátorovi se po přihlášení zobrazí přehled všech rezervací zobrazený jako seznam pracovních míst a jejich status po dnech. Bude moci provádět rezervaci místa za klienta a spravovat existující rezervace. Zároveň bude moci editovat parametry pracovních míst, mazat, přidávat nové nebo dočasně nějaké místo deaktivovat. Rezervace bude po zaplacení ručně převádět do stavu zaplaceno.

### Návrh databázového schématu

Všechna IDs se budou generovat v aplikaci. Heslo bude uloženo jako hash a pro zvýšení bezpečnosti přidána password salt. 

![image](https://user-images.githubusercontent.com/21370636/114836700-38b55400-9dd3-11eb-82c9-45242a0277da.png)

### Architektura

**FRONTEND**
HTML, CSS, Bootstrap

**BACKEND**
PHP, MySQL

Frontend nebude obsahovat žádné dynamické prvky. 

### Návrh wireframů uživatelského rozhraní

Hlavní stránka (před přihlášením)
![image](https://user-images.githubusercontent.com/21370636/114837140-aceff780-9dd3-11eb-9f5a-cebae07a1a8d.png)

Sign up
![image](https://user-images.githubusercontent.com/21370636/114837157-b2e5d880-9dd3-11eb-9121-84308e16363d.png)

Log in
![image](https://user-images.githubusercontent.com/21370636/114837100-9fd30880-9dd3-11eb-9197-2628336818c8.png)

Klient po přihlášení - My reservations
![image](https://user-images.githubusercontent.com/21370636/114837176-b8432300-9dd3-11eb-8ea7-7fbaef32d595.png)

Klient po přihlášení - Vytvoření nové rezervace
![image](https://user-images.githubusercontent.com/21370636/114837199-be390400-9dd3-11eb-9398-85bcc8d66bed.png)

![image](https://user-images.githubusercontent.com/21370636/114837214-c2652180-9dd3-11eb-8dba-3f78e14c7710.png)

Administrátor po přihlášení - Reservations
![image](https://user-images.githubusercontent.com/21370636/114837231-c6913f00-9dd3-11eb-9eef-f46f60da71f6.png)

Administrátor po přihlášení - Vytvoření nové rezervace
![image](https://user-images.githubusercontent.com/21370636/114837248-ca24c600-9dd3-11eb-99e1-e489ec3f8e0b.png)

Administrátor po přihlášení - Workplaces
![image](https://user-images.githubusercontent.com/21370636/114837266-cdb84d00-9dd3-11eb-87af-1440a7b5ef91.png)

**Comment by nvbach91** [comment]
#253
