### ISSUE TITLE
sp-krij09

### ISSUE THREAD

**Issue by kubakriz** [nvbach91/4IZ278-2020-2021-LS#194]
[Semestrální práce.pdf](https://github.com/nvbach91/4IZ278-2020-2021-LS/files/6327961/Semestralni.prace.pdf)

**Comment by nvbach91** [comment]
- chybi wireframy
- pro databazove schema pouzivejte nejakou standardni notaci UML kterou pouzivate v predmetu databaze
- discount evidujte jako procentualni hodnotu v dalsim sloupci v tabulce game, ne jako dalsi tabulku
- veci jako adresa a zpusob uhrady jsou potreba u objednavky ale vy je mate v checkout

**Comment by kubakriz** [comment]
* Wireframe jsme dodal v textové podobě, dočetl jsem se, že i takto je to validní. 
* Databáze v průběhu dneška předělám
* Stejně tak tyto dvě tabulky. :-)

**Comment by kubakriz** [comment]
Posílám upravené :-)

[Semestrální práce.pdf](https://github.com/nvbach91/4IZ278-2020-2021-LS/files/6372510/Semestralni.prace.pdf)

**Comment by nvbach91** [comment]
zkuste to kreslit v wireframe.cc, figma.com nebo https://app.diagrams.net/

**Comment by kubakriz** [comment]
[Semestrální práce.pdf](https://github.com/nvbach91/4IZ278-2020-2021-LS/files/6404144/Semestralni.prace.pdf)

Zde nahrávám finální, už je to snad vše :-)

**Comment by nvbach91** [comment]
#243
