### ISSUE TITLE
sp-sesm00

### ISSUE THREAD

**Issue by sesm00** [nvbach91/4IZ278-2020-2021-LS#196]
Odevzdávám návrh semestrální práce v souporu níže
[sp_sesm00.pdf](https://github.com/nvbach91/4IZ278-2020-2021-LS/files/6372971/sp_sesm00.pdf)

**Comment by nvbach91** [comment]
- myslim ze tabulka delivery addresses potrebuje referenci na vlasnika usera
- dodaci addresa nepotrebuje vedet do jake objednavky patri, staci ze objednavka ma nejakou dodaci adresu

**Comment by sesm00** [comment]
> 
> 
>     * myslim ze tabulka delivery addresses potrebuje referenci na vlasnika usera
> 
>     * dodaci addresa nepotrebuje vedet do jake objednavky patri, staci ze objednavka ma nejakou dodaci adresu

upraveno dle připomínek

**Comment by nvbach91** [comment]
#238
