### ISSUE TITLE
sp-tson00

### ISSUE THREAD

**Issue by tson00** [nvbach91/4IZ278-2020-2021-LS#197]
# Sousedi
Aplikace by umožnovala studentům na koleji půjčovat věci navzájem. 
## Uživatel
Může zadávat zboží, může půjčit. Pro půjčování zboží je nutná registrace, aby studenti měli jistotu komu.
## Zboží
Zboží musí mít buď uvedenou cenu. Uživatel v podstatě toho může zadat a půjčit kolik se mu bude chtít.
## Skupiny zboží
1. Hobby
2. Nábytek
3. Oblečení
4. Škola
5. Elektro
6. Ostatní

## Univerzity:
Jedná se o lokality ve kterých studenty bydlí, pro jednoduché filtrování.
#### Kolej
- Eislerova kolej (Jarov III.F)
- Kolej Blanice
- Kolej Jarov II
- Kolej Vltava
- Palachova kolej (Jarov I)
- Rooseveltova kolej
- Švecova kolej (Jindřichův Hradec)
- Thalerova kolej (Jarov III.G)
- University Hotel (Jarov I.E)

#### Kolej
- Koleje Strahov
- Koleje Podolí
- Dejvická kolej 
- Kolej Orlík
- Sinkuleho kolej
- Hlávkova kolej
- Masarykova kolej

#### Kolej
- Kolej A
- Kolej BCD
- Kolej EFG
- Kolej JIH

## Návrh architektury
- PHP
- MySQL
- Bootstrap
- CSS
- HTML

 ## Wireframe
### Úvodní stránka
Na úvodní stránce budou zobrazeny všichni zboží. U každého zboží bude link na podrobnosti
![1](https://user-images.githubusercontent.com/32293231/115108184-53bccb00-9f6f-11eb-9e44-1e6cf64961b0.png)
### Podrobnosti zboží
![2](https://user-images.githubusercontent.com/32293231/115108280-dba2d500-9f6f-11eb-828e-33ae9c847e8c.png)
### Registrace
![3](https://user-images.githubusercontent.com/32293231/115108317-160c7200-9f70-11eb-81fe-9717a9709fb1.png)
### Profil
Bude moct změnit údaje a uložit 
![4](https://user-images.githubusercontent.com/32293231/115108343-448a4d00-9f70-11eb-80de-05df1b46f247.png)
### Přihlášení
![5](https://user-images.githubusercontent.com/32293231/115108376-6d124700-9f70-11eb-8785-393e2520e839.png)
### Úvodní stránka přihlášeného uživatele
![6](https://user-images.githubusercontent.com/32293231/115108410-97640480-9f70-11eb-93c5-824b0fbe0fd9.png)
### Výpůjčky
Uživatel se může podívat jaké má výpůjčky a může jich vrátit
![7](https://user-images.githubusercontent.com/32293231/115108465-df832700-9f70-11eb-81fe-55830a8ecbae.png)
### Moje zboží
Uživatel vidí seznam aktuálních zboží co přidal, vidí v jakém jsou stavu zdá jsem vypůjčené nebo jsou k vracení nebo jsou aktivní. Může to zboží upravit nebo přidat nové.
![8](https://user-images.githubusercontent.com/32293231/115108575-8b2c7700-9f71-11eb-90bf-48fc236ea60c.png)
![9](https://user-images.githubusercontent.com/32293231/115108593-a0090a80-9f71-11eb-849b-712ca5f2da70.png)
![10](https://user-images.githubusercontent.com/32293231/115108626-c9c23180-9f71-11eb-9ce4-dca9b527f93c.png)
### Požadavky
Uživatel bude moct po předání zboží schválit stav zboží
![11](https://user-images.githubusercontent.com/32293231/115108677-0ee66380-9f72-11eb-8b09-6ba2757ac67b.png)

## Databáze
![Untitled Diagram (1)](https://user-images.githubusercontent.com/32293231/115110307-faf32f80-9f7a-11eb-897f-6d004e8a0e97.jpg)

**Comment by nvbach91** [comment]
- nazvy tabulek a sloupcu v db prelozte do anglictiny
- chybi tabulka pomoci ktere budete sledovat komu je vypujceno zbozi (vztah M:N)

**Comment by tson00** [comment]
@nvbach91 
### Update
- přejmenovala jsem tabulky
- vztah M:N nejsem si jistá zdá jsem ho pochopila správně

![Untitled Diagram (2)](https://user-images.githubusercontent.com/32293231/116140489-ae74c600-a6d7-11eb-89a4-17a261e71d52.png)

**Comment by nvbach91** [comment]
Ano, avsak pro jistotu si zkuste vygenerovat priklady dat, viz LAB06

**Comment by nvbach91** [comment]
#269
