### ISSUE TITLE
sp_umam00

### ISSUE THREAD

**Issue by mega-maga** [nvbach91/4IZ278-2020-2021-LS#199]
Posílám návrh semestrální práce "Noter..." 
[Noter....pdf](https://github.com/nvbach91/4IZ278-2020-2021-LS/files/6329312/Noter.pdf)

**Comment by nvbach91** [comment]
- z Users k Notes ma byt vztah 1 - 0..N
- to same z Users k Projects
- v Tabulce Projects ma byt sloupec OWNER_ID misto ID_USER, nebo ID_USER a vztah mezi tabulkou Users a Project smazte, a v tabulce USER_TO_PROJECT pridejte roli uzivatele

**Comment by mega-maga** [comment]
[Noter....pdf](https://github.com/nvbach91/4IZ278-2020-2021-LS/files/6372161/Noter.pdf)
Přikládám opravený návrh SP

**Comment by nvbach91** [comment]
#248
