### ISSUE TITLE
Tech stack

### ISSUE THREAD

**Issue by jirkavrba** [nvbach91/4IZ278-2020-2021-LS#2]
Je možné použít i jiný tech stack než XAMPP? 

Mám konkrétně na mysli nativní linux distribuci Apache 2 + PHP + self hosted mysql databázi, 
mám již na počítači nainstalovaný dev environment pro PHP 7.4, tak bych tam pak měl duplicitní instalace...

**Comment by nvbach91** [comment]
Budu to ukazovat na Windows přes XAMPP, ale není to podmínkou k absolvování předmětu.
