### ISSUE TITLE
sp-lamj00

### ISSUE THREAD

**Issue by vingly** [nvbach91/4IZ278-2020-2021-LS#201]
[componentoro.pdf](https://github.com/nvbach91/4IZ278-2020-2021-LS/files/6329524/componentoro.pdf)

**Comment by nvbach91** [comment]
- myslim ze vam chybi tabulka vyrobcu pro trideni produktu podle vyrobce
- navic total_price by mela vzdycky vychazet z polozek, ktere do objednavky patri, ne jako staticka hodnota

**Comment by nvbach91** [comment]
#255
