### ISSUE TITLE
sp-brum08

### ISSUE THREAD

**Issue by wellsinik** [nvbach91/4IZ278-2020-2021-LS#209]
Zadání semestrální práce Brumcoma.
[sp-brum08.pdf](https://github.com/nvbach91/4IZ278-2020-2021-LS/files/6331586/sp-brum08.pdf)

**Comment by nvbach91** [comment]
- prosim prejmenovat nazvy tabulek a sloupcu do anglictiny

**Comment by wellsinik** [comment]
Sloupce i tabulky přejmenovány.
[sp-brum08.pdf](https://github.com/nvbach91/4IZ278-2020-2021-LS/files/6451807/sp-brum08.pdf)
