### ISSUE TITLE
sp-pesa06

### ISSUE THREAD

**Issue by pesa06** [nvbach91/4IZ278-2020-2021-LS#211]
[sem_pesa06.pdf](https://github.com/nvbach91/4IZ278-2020-2021-LS/files/6331757/sem_pesa06.pdf)
[cechie-dubec-master (1).zip](https://github.com/nvbach91/4IZ278-2020-2021-LS/files/6331758/cechie-dubec-master.1.zip)
[4IZ110_semestralka.pdf](https://github.com/nvbach91/4IZ278-2020-2021-LS/files/6331759/4IZ110_semestralka.pdf)

**Comment by nvbach91** [comment]
Z prace v zipu prosim udelejte pilotni pull request

**Comment by pesa06** [comment]
https://github.com/pesa06/sem-project práce na bude probíhat v tomto repozitáři, přizval jsem Vás do něj. Soubory ze zipu jsem nahrál do branche main, nový kód budu pushovat do separátního branche, aby bylo přehledně vidět, co jsem přidal a co tam již bylo.

**Comment by nvbach91** [comment]
#266
