### ISSUE TITLE
sp-vond07

### ISSUE THREAD

**Issue by vond07** [nvbach91/4IZ278-2020-2021-LS#217]
Zadání
[Realitní kancelář.pdf](https://github.com/nvbach91/4IZ278-2020-2021-LS/files/6331972/Realitni.kancelar.pdf)

**Comment by nvbach91** [comment]
- prosim nazvy tabulek a sloupcu prelozit do anglictiny

**Comment by vond07** [comment]
[Realitní kancelář.docx](https://github.com/nvbach91/4IZ278-2020-2021-LS/files/6405337/Realitni.kancelar.docx)

**Comment by nvbach91** [comment]
#270
