### ISSUE TITLE
sp-ngut37

### ISSUE THREAD

**Issue by ngut37** [nvbach91/4IZ278-2020-2021-LS#228]
[ngut37.pdf](https://github.com/nvbach91/4IZ278-2020-2021-LS/files/6373050/ngut37.pdf)

**Comment by nvbach91** [comment]
- predpokladam ze nebudete ukladat heslo v plaintextu do databaze a rameny budou mit i nejakou cenu
- prace musi obsahovat i rozhrani pro upravu produktu pro admina - opravneni a viceuzivatelsky pristup
- vytvorte a dodejte zbytek wireframu - kosik, objednavka, rozhrani pro pridavani produktu/kategorii

**Comment by ngut37** [comment]
Opravy:
- pridan feature s rolema (napr: `ADMIN` nebo `EDITOR`)
- pridany zbytek mockupu stranek

Soubor: [sp-ngut37_v2.pdf](https://github.com/nvbach91/4IZ278-2020-2021-LS/files/6410368/sp-ngut37_v2.pdf)
