### ISSUE TITLE
Laragon namiesto XAMPP

### ISSUE THREAD

**Issue by socka25** [nvbach91/4IZ278-2020-2021-LS#3]
Dobrý večer,
chcel som sa Vás len opýtať, či by Vám neprekážalo ak by som používal Laragon namiesto XAMPP. Mal som to tak už v PC nainštalované dlhšie (podľa tutoriálu) a nakoľko nie som v týchto veciach dostatočne zručný, keď som sa pokúšal inštalovať si namiesto Laragonu XAMPP, tak mi vyskočili errory vo VS Code, kde už mám PHP nastavené a aj pri otvorení projektov, ktoré som už mal rozpracované. Okrem tohoto softwaru, však budem mať všetky ostatné, požadované na MS Teams, k dispozícií. Ak by to však v priebehu semestra malo spôsobiť ťažkosti mne alebo dokonca Vám, tak sa pokúsim to nejak napraviť, či už sám alebo prípadne s Vašou pomocou. Ďakujem za odpoveď

**Comment by nvbach91** [comment]
Viz https://github.com/nvbach91/4IZ278-2020-2021-LS/issues/2

To je na Vás, pokud už jste zvkylý na něco jiného, tak klidně, ale bude to trochu jiné než to, co budu ukazovat na cvičeních. Pokud ale budete mít nějaký problém s tím Laragonem, tak budete muset si sám najít řešení. Uvidíte na prvním cvičení, jestli se Vám to vyplatí nebo ne.
