### ISSUE TITLE
sp-vrbj04

### ISSUE THREAD

**Issue by jirkavrba** [nvbach91/4IZ278-2020-2021-LS#96]
Návrh zadání semestrální práce k předmětu 4IZ278

Jiří Vrba (`vrbj04`), LS 2020/2021

# Flashcard aplikace

Aplikace bude umožňovat jejím uživatelům zaregistrovat si účet a poté vytvářet kolekce. 
Kolekci si lze představit jako např. kategorii, předmět, ...

Do každé kolekce může pak uživatel vytvářet balíčky flashcards. 
Flashcard je jednoduchá kartička s otázkou na jedné straně a odpovědí na druhé. 

Každý takový balíček může být nastaven jako soukromý (uvidí ho pouze uživatel, který ho vytvořil) nebo 
veřejný (ostatní uživatelé aplikace / nepřihlášení uživatelé ho uvidí, budou si ho moci spustit, ale 
nebudou už moci balíček upravovat).

Každá kolekce může obsahovat prakticky neomezené množství balíčků a může být nastavená buď jako soukromá,
nebo jako veřejná (každý přihlášený uživatel do ní může přidávat balíčky, každý může upravovat pouze svoje
balíčky). 

Aplikace bude umožňovat exportovat kartičky ve formátu pro tisk, případně import a export balíčků přes 
vhodný formát (nejspíše JSON).

Každý uživatel bude mít možnost ukládat si balíčky jako svoje oblíbené, a budou se mu zobrazovat jako
odkazy na hlavní stránce.

Otázky i odpovědi mohou obsahovat LaTeX kód, který bude následně renderován v testeru, což umožňuje psaní
kvalitních testerů např. pro procvičování k matematickým předmětům.

## Návrh databázového schématu

![Schéma databáze](http://www.plantuml.com/plantuml/png/jTD1Ry8W50VmEv_YnQE9tNqnncI9bvrssBbXzB4IALHup1cxxpwqKkpIf8TjD_xmxyjFIxUUkAFGQ5Qh2a4e9pGolrUcvOute9L1EhK8rb5j6KD3YawmUFNe5i0zXBY0CmDONbQbgk0HJ6ZUukvw_Ou67IUiDflOMArIpV06Ou_mas8h67K8UAqiM-xzqReA7i3oG3MGtQEvTTbN1kmqzxNWhhegP4ezPOXpdcdsxhd7a2ATd35Nw8LJBIbh9ZpympeLHuCSo-IDbCxBFyBbCHFdap1XjKPnuVSoyLEM2x-ZvJapjgUnA3_NotB-f_SuTR5U0lf1T8WXUrAQqSo-7HZcPXGt_eWkPwtClYHRneJES5qwz3OuWNVawxVNTKLXptV_tMXRod4KZ4a9HT5r-PuoAVgTknaihuTdSp-jqb7wEMoBfWgD_WO0)

Kde tabulky `User`, `Collection`, `Flashcard` a `Question` budou realizovány jako Eloquent model a vazby
mezi nimi (tabulky `Favorited_collection`, `Favorited_flashcard` a všechny foreign key) jako definice
na modelu pomocí metod `belongsTo`, `hasMany`, `hasOne`, ...

## Architektura
Chtěl bych použít Laravel, Mysql (s Eloquent ORM), deploy bude probíhat na Heroku, kde 
se dá automaticky napojit Github, celá stránka pak bude realizována buď jako Vue.js SPA s dotazováním na API, nebo pomocí Blade šablon v Laravelu.

Bude se jednat o API s následující strukturou endpointů:

Např. `GET /api/collections/` - pokud je uživatel přihlášený, osobní pohled (tj. i private kolekce, favorite kolekce), pokud není příhlášený, výpis všech public kolekcí
```json
{
  "collections": [
     {
       "data kolekce" :  {},
       "data o autorovi": {}
     }
  ]
}
```

Po přihlášení se zpřístupní klasické CRUD metody pro kolekce, flashcardy a otázky v rámci flashcardu

Pro čtení dat:
```
GET /api/collections/:collection_id
GET /api/collections/:collection_id/flashcards/:flashcard_id
GET /api/collections/:collection_id/flashcards/:flashcard_id/questions/:question_id
```

Pak po příhlášení budou přístupné enpointy

Pro přidávání nových dat
```
POST /api/collections
POST /api/collections/:collection_id/flashcards
POST /api/collections/:collection_id/flashcard/:flashcard_id/questions
```

Pro uložení změn
```
PUT /api/collections/:collection_id/edit
PUT /api/collections/:collection_id/flashcards/:flashcard_id/edit
PUT /api/collections/:collection_id/flashcards/:flashcard_id/questions/:question_id/edit
```

Pro smazání dat
```
DELETE /api/collections/:collection_id
DELETE /api/collections/:collection_id/flashcards/:flashcard_id
DELETE /api/collections/:collection_id/flashcards/:flashcard_id/questions/:question_id
```

Pro označení kolekce jako favorite/unfavorite
```
POST /api/collections/:collection_id/favorite
POST /api/collections/:collection_id/unfavorite
```

### Hlavní stránka (před přihlášením)
![image](https://user-images.githubusercontent.com/14146321/110924389-44b87c80-8322-11eb-8d81-68604d194e4a.png)

### Hlavní stránka (po přihlášení)
![image](https://user-images.githubusercontent.com/14146321/110924428-4e41e480-8322-11eb-89fc-3debc1e9f419.png)

### Zobrazení flashcardu
![image](https://user-images.githubusercontent.com/14146321/110924448-5568f280-8322-11eb-95b4-5dd76674317e.png)

### Zobrazení testeru
![image](https://user-images.githubusercontent.com/14146321/110924473-5dc12d80-8322-11eb-9087-7c82596cad7f.png)

**Comment by nvbach91** [comment]
Je to bezva az na to ze nemate zadny M:N vztah mezi tabulkami, resp. vztah ktery vypada takto A - 1:N - B - N:1 - C, coz bych ocekaval, ze A=Users, B=Collection, C=Flashcard

**Comment by jirkavrba** [comment]
Chápu teda správně, že by to mělo být Uživatel může mít N kolekcí, kde do kolekce patří jedna flashcard, kde flashcard může patřít do více kolekcí?

**Comment by jirkavrba** [comment]
V konceptuálním modelu tedy nějak takto:
![image](https://user-images.githubusercontent.com/14146321/114090346-961f4180-98b7-11eb-9e26-2e0bcca1b3a2.png)

**Comment by jirkavrba** [comment]
Myslím si že větší smysl by mělo přidat funkcionalitu "Follow user" kde by pak vznikla právě vazba že N uživatelů sleduje M jiných uživatelů a naopak:
![image](https://user-images.githubusercontent.com/14146321/114091890-886abb80-98b9-11eb-9d63-1eec3d08ce78.png)

**Comment by nvbach91** [comment]
jako priklad jsem user U1 a mam 
- kolekci C1 s kartami K1, K2, K3
- kolekci C2 s kartami K3, K4, K5

vy jste user U2 a mate 
- kolekci C3 s kartami K1, K2, K3
- kolekci C4 s kartami K3, K4, K5

v databazi budete ukladat:

users data:
U1
U2

collection data:
C1 U1 K1
C1 U1 K2
C1 U1 K3
C2 U1 K3
C2 U1 K4
C2 U1 K5
C3 U2 K1
C3 U2 K2
C3 U2 K3
C4 U1 K3
C4 U1 K4
C4 U1 K5

card data:
K1
K2
K3
K4
K5

co se tyce user follow users jestli chcete tak muzete mit tabulku relationship s 2x FK follower_id a followee_id, a vztah bude 2x 1:N smerem od users k relationship

**Comment by nvbach91** [comment]
#225
